### ISSUE TITLE
Has this example become obsolete due to API changes?

### ISSUE THREAD

**Issue by sychan** [minrk/singlecell#1]
Hi,
   I work with Shreyas Cholia and Matt Henderson at LBL, and just tried to run the singlecell example against the current 1.0-dev branch of IPython (up to commit 6c864917746d41814534986080b3e1d4e21ee254 ) and even after a few rounds of changing the import statements for what seems to be refactoring of the module namespace, it still won't run. Here's the current error:

Traceback (most recent call last):
  File "singlecell.py", line 46, in <module>
    from IPython.frontend.html.notebook.notebookapp import (
ImportError: cannot import name _kernel_action_regex

   Before I wander too much further down this rabbit hole, am I just doing something wrong, or has the 1.0-dev basically made this example obsolete?

   Thanks,
   Steve

**Comment by sychan** [comment]
Never mind - I managed to resolve all of the namespace issues and it works perfectly.

**Comment by minrk** [comment]
If you want to make a PR with the name changes, that would be great, since you already solved it.

**Comment by sychan** [comment]
I'll push my version to github, but I realized the other day that I pretty much ignored the Bessel function example (I was only interested in the singlecell demo) and while there are no errors, there's also no plot.

**Comment by minrk** [comment]
No worries, thanks. I'll update it all once 1.0 is settled.
