### ISSUE TITLE
ImportError: IPython.kernel has been replaced by IPython.parallel.

### ISSUE THREAD

**Issue by decentral1se** [minrk/singlecell#3]
╭─lwm@lwm-Latitude-D620  ~/repos/singlecell  ‹master› 
╰─$ python singlecell.py                                                                                                                                                          1 ↵
Traceback (most recent call last):
  File "singlecell.py", line 39, in <module>
    from IPython.kernel.multikernelmanager import MultiKernelManager
  File "/usr/lib/python2.7/dist-packages/IPython/kernel/**init**.py", line 10, in <module>
    raise ImportError(**doc**)
ImportError: IPython.kernel has been replaced by IPython.parallel.

The previous version of IPython's parallel library was located at this
location (IPython.kernel). It has been moved to the IPython.parallel
subpackage and has been refactored to use zeromq/pyzmq instead of twisted.

Please see INSERT URL for further details.

╭─lwm@lwm-Latitude-D620  ~/repos/singlecell  ‹master› 
╰─$ python --version                                                                                                                                                              1 ↵
Python 2.7.4

╭─lwm@lwm-Latitude-D620  ~/repos/singlecell  ‹master› 
╰─$ cat /proc/version  
Linux version 3.8.0-31-generic (buildd@aatxe) (gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1) ) #46-Ubuntu SMP Tue Sep 10 19:56:49 UTC 2013

**Comment by minrk** [comment]
singlecells requires IPython ≥ 1.0

**Comment by decentral1se** [comment]
right, well shouldn't you write that somewhere in the readme?

**Comment by minrk** [comment]
Indeed I should. Done.
